
final:
	g++ test.cpp Vbo.cpp Ibo.cpp Vao.cpp VertexBufferLayout.cpp Shader.cpp -o test -std=c++11 -Wall -lGL -lGLU -lglut -lGLEW -lglfw -lX11 -lXxf86vm -lXrandr -lpthread -lXi -ldl -lXinerama -lXcursor
	./test
